-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.AssetPreviousValues exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


createdAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.AssetPreviousValues
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| Original File Name
-}
fileName : SelectionSet String Api.Object.AssetPreviousValues
fileName =
    Object.selectionForField "String" "fileName" [] Decode.string


{-| The File Handle
-}
handle : SelectionSet String Api.Object.AssetPreviousValues
handle =
    Object.selectionForField "String" "handle" [] Decode.string


{-| The height of the file in case it is an image
-}
height : SelectionSet (Maybe Float) Api.Object.AssetPreviousValues
height =
    Object.selectionForField "(Maybe Float)" "height" [] (Decode.float |> Decode.nullable)


id : SelectionSet Api.ScalarCodecs.Id Api.Object.AssetPreviousValues
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The Mime Type
-}
mimeType : SelectionSet (Maybe String) Api.Object.AssetPreviousValues
mimeType =
    Object.selectionForField "(Maybe String)" "mimeType" [] (Decode.string |> Decode.nullable)


{-| The Size Of The File
-}
size : SelectionSet Float Api.Object.AssetPreviousValues
size =
    Object.selectionForField "Float" "size" [] Decode.float


updatedAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.AssetPreviousValues
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| The Url Of The Asset
-}
url : SelectionSet String Api.Object.AssetPreviousValues
url =
    Object.selectionForField "String" "url" [] Decode.string


{-| The width of the file in case it is an image
-}
width : SelectionSet (Maybe Float) Api.Object.AssetPreviousValues
width =
    Object.selectionForField "(Maybe Float)" "width" [] (Decode.float |> Decode.nullable)
