-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.FilmPreviousValues exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


createdAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.FilmPreviousValues
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| The name of the director of this film.
-}
director : SelectionSet (Maybe String) Api.Object.FilmPreviousValues
director =
    Object.selectionForField "(Maybe String)" "director" [] (Decode.string |> Decode.nullable)


{-| The episode number of this film.
-}
episodeId : SelectionSet Int Api.Object.FilmPreviousValues
episodeId =
    Object.selectionForField "Int" "episodeId" [] Decode.int


id : SelectionSet Api.ScalarCodecs.Id Api.Object.FilmPreviousValues
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| indicates if the record is published
-}
isPublished : SelectionSet Bool Api.Object.FilmPreviousValues
isPublished =
    Object.selectionForField "Bool" "isPublished" [] Decode.bool


{-| The opening paragraphs at the beginning of this film.
-}
openingCrawl : SelectionSet (Maybe String) Api.Object.FilmPreviousValues
openingCrawl =
    Object.selectionForField "(Maybe String)" "openingCrawl" [] (Decode.string |> Decode.nullable)


{-| The names of the producers of this film.
-}
producers : SelectionSet (Maybe (List String)) Api.Object.FilmPreviousValues
producers =
    Object.selectionForField "(Maybe (List String))" "producers" [] (Decode.string |> Decode.list |> Decode.nullable)


{-| The ISO 8601 date format of film release at original creator country.
-}
releaseDate : SelectionSet (Maybe Api.ScalarCodecs.DateTime) Api.Object.FilmPreviousValues
releaseDate =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "releaseDate" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


{-| The title of this film
-}
title : SelectionSet String Api.Object.FilmPreviousValues
title =
    Object.selectionForField "String" "title" [] Decode.string


updatedAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.FilmPreviousValues
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
