-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.PlanetPreviousValues exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The climate of this planet.
-}
climate : SelectionSet (Maybe (List String)) Api.Object.PlanetPreviousValues
climate =
    Object.selectionForField "(Maybe (List String))" "climate" [] (Decode.string |> Decode.list |> Decode.nullable)


createdAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.PlanetPreviousValues
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| The diameter of this planet in kilometers.
-}
diameter : SelectionSet (Maybe Int) Api.Object.PlanetPreviousValues
diameter =
    Object.selectionForField "(Maybe Int)" "diameter" [] (Decode.int |> Decode.nullable)


{-| A number denoting the gravity of this planet, where "1" is normal or 1 standard G. "2" is twice or 2 standard Gs. "0.5" is half or 0.5 standard Gs.
-}
gravity : SelectionSet (Maybe String) Api.Object.PlanetPreviousValues
gravity =
    Object.selectionForField "(Maybe String)" "gravity" [] (Decode.string |> Decode.nullable)


id : SelectionSet Api.ScalarCodecs.Id Api.Object.PlanetPreviousValues
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| indicates if the record is published
-}
isPublished : SelectionSet Bool Api.Object.PlanetPreviousValues
isPublished =
    Object.selectionForField "Bool" "isPublished" [] Decode.bool


{-| The name of the planet
-}
name : SelectionSet String Api.Object.PlanetPreviousValues
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The number of standard days it takes for this planet to complete a single orbit of its local star.
-}
orbitalPeriod : SelectionSet (Maybe Int) Api.Object.PlanetPreviousValues
orbitalPeriod =
    Object.selectionForField "(Maybe Int)" "orbitalPeriod" [] (Decode.int |> Decode.nullable)


{-| The average population of sentient beings inhabiting this planet.
-}
population : SelectionSet (Maybe Float) Api.Object.PlanetPreviousValues
population =
    Object.selectionForField "(Maybe Float)" "population" [] (Decode.float |> Decode.nullable)


{-| The number of standard hours it takes for this planet to complete a single rotation on its axis.
-}
rotationPeriod : SelectionSet (Maybe Int) Api.Object.PlanetPreviousValues
rotationPeriod =
    Object.selectionForField "(Maybe Int)" "rotationPeriod" [] (Decode.int |> Decode.nullable)


{-| The percentage of the planet surface that is naturally occurring water or bodies of water.
-}
surfaceWater : SelectionSet (Maybe Float) Api.Object.PlanetPreviousValues
surfaceWater =
    Object.selectionForField "(Maybe Float)" "surfaceWater" [] (Decode.float |> Decode.nullable)


{-| The terrain of this planet.
-}
terrain : SelectionSet (Maybe (List String)) Api.Object.PlanetPreviousValues
terrain =
    Object.selectionForField "(Maybe (List String))" "terrain" [] (Decode.string |> Decode.list |> Decode.nullable)


updatedAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.PlanetPreviousValues
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
