-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.RemoveFromPeoplePlanetPayload exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


residentsPerson : SelectionSet decodesTo Api.Object.Person -> SelectionSet (Maybe decodesTo) Api.Object.RemoveFromPeoplePlanetPayload
residentsPerson object_ =
    Object.selectionForCompositeField "residentsPerson" [] object_ (identity >> Decode.nullable)


homeworldPlanet : SelectionSet decodesTo Api.Object.Planet -> SelectionSet (Maybe decodesTo) Api.Object.RemoveFromPeoplePlanetPayload
homeworldPlanet object_ =
    Object.selectionForCompositeField "homeworldPlanet" [] object_ (identity >> Decode.nullable)
