-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.StarshipPreviousValues exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The maximum number of kilograms that this starship can transport.
-}
cargoCapacity : SelectionSet (Maybe Float) Api.Object.StarshipPreviousValues
cargoCapacity =
    Object.selectionForField "(Maybe Float)" "cargoCapacity" [] (Decode.float |> Decode.nullable)


{-| The class of this starship, such as "Starfighter" or "Deep Space Mobile Battlestation"
-}
class : SelectionSet (Maybe String) Api.Object.StarshipPreviousValues
class =
    Object.selectionForField "(Maybe String)" "class" [] (Decode.string |> Decode.nullable)


{-| The maximum length of time that this starship can provide consumables for its entire crew without having to resupply.
-}
consumables : SelectionSet (Maybe String) Api.Object.StarshipPreviousValues
consumables =
    Object.selectionForField "(Maybe String)" "consumables" [] (Decode.string |> Decode.nullable)


{-| The cost of this starship new, in galactic credits.
-}
costInCredits : SelectionSet (Maybe Float) Api.Object.StarshipPreviousValues
costInCredits =
    Object.selectionForField "(Maybe Float)" "costInCredits" [] (Decode.float |> Decode.nullable)


createdAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.StarshipPreviousValues
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| The number of personnel needed to run or pilot this starship.
-}
crew : SelectionSet (Maybe Int) Api.Object.StarshipPreviousValues
crew =
    Object.selectionForField "(Maybe Int)" "crew" [] (Decode.int |> Decode.nullable)


{-| The class of this starships hyperdrive.
-}
hyperdriveRating : SelectionSet (Maybe Float) Api.Object.StarshipPreviousValues
hyperdriveRating =
    Object.selectionForField "(Maybe Float)" "hyperdriveRating" [] (Decode.float |> Decode.nullable)


id : SelectionSet Api.ScalarCodecs.Id Api.Object.StarshipPreviousValues
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| indicates if the record is published
-}
isPublished : SelectionSet Bool Api.Object.StarshipPreviousValues
isPublished =
    Object.selectionForField "Bool" "isPublished" [] Decode.bool


{-| The length of this starship in meters.
-}
length : SelectionSet (Maybe Float) Api.Object.StarshipPreviousValues
length =
    Object.selectionForField "(Maybe Float)" "length" [] (Decode.float |> Decode.nullable)


{-| The manufacturer of this starship.
-}
manufacturer : SelectionSet (Maybe (List String)) Api.Object.StarshipPreviousValues
manufacturer =
    Object.selectionForField "(Maybe (List String))" "manufacturer" [] (Decode.string |> Decode.list |> Decode.nullable)


{-| The maximum speed of this starship in the atmosphere. null if this starship is incapable of atmospheric flight.
-}
maxAtmospheringSpeed : SelectionSet (Maybe Int) Api.Object.StarshipPreviousValues
maxAtmospheringSpeed =
    Object.selectionForField "(Maybe Int)" "maxAtmospheringSpeed" [] (Decode.int |> Decode.nullable)


{-| The Maximum number of Megalights this starship can travel in a standard hour. A "Megalight" is a standard unit of distance and has never been defined before within the Star Wars universe.
-}
mglt : SelectionSet (Maybe Int) Api.Object.StarshipPreviousValues
mglt =
    Object.selectionForField "(Maybe Int)" "mglt" [] (Decode.int |> Decode.nullable)


{-| The name of this starship. The common name, such as "Death Star".
-}
name : SelectionSet String Api.Object.StarshipPreviousValues
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The number of non-essential people this starship can transport.
-}
passengers : SelectionSet (Maybe Int) Api.Object.StarshipPreviousValues
passengers =
    Object.selectionForField "(Maybe Int)" "passengers" [] (Decode.int |> Decode.nullable)


updatedAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.StarshipPreviousValues
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
