-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.ModelMutationType_ exposing (..)

import Json.Decode as Decode exposing (Decoder)


type ModelMutationType_
    = Created
    | Updated
    | Deleted


list : List ModelMutationType_
list =
    [ Created, Updated, Deleted ]


decoder : Decoder ModelMutationType_
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "CREATED" ->
                        Decode.succeed Created

                    "UPDATED" ->
                        Decode.succeed Updated

                    "DELETED" ->
                        Decode.succeed Deleted

                    _ ->
                        Decode.fail ("Invalid ModelMutationType_ type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : ModelMutationType_ -> String
toString enum =
    case enum of
        Created ->
            "CREATED"

        Updated ->
            "UPDATED"

        Deleted ->
            "DELETED"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe ModelMutationType_
fromString enumString =
    case enumString of
        "CREATED" ->
            Just Created

        "UPDATED" ->
            Just Updated

        "DELETED" ->
            Just Deleted

        _ ->
            Nothing
