-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.PersonEyeColor exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The eye color of this person. Will be "UNKNOWN" if not known or null if the person does not have an eye.
-}
type PersonEyeColor
    = Unknown
    | Blue
    | Yellow
    | Red
    | Brown
    | Bluegrey
    | Black
    | Orange
    | Hazel
    | Pink
    | Gold
    | Green
    | White
    | Dark


list : List PersonEyeColor
list =
    [ Unknown, Blue, Yellow, Red, Brown, Bluegrey, Black, Orange, Hazel, Pink, Gold, Green, White, Dark ]


decoder : Decoder PersonEyeColor
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "UNKNOWN" ->
                        Decode.succeed Unknown

                    "BLUE" ->
                        Decode.succeed Blue

                    "YELLOW" ->
                        Decode.succeed Yellow

                    "RED" ->
                        Decode.succeed Red

                    "BROWN" ->
                        Decode.succeed Brown

                    "BLUEGREY" ->
                        Decode.succeed Bluegrey

                    "BLACK" ->
                        Decode.succeed Black

                    "ORANGE" ->
                        Decode.succeed Orange

                    "HAZEL" ->
                        Decode.succeed Hazel

                    "PINK" ->
                        Decode.succeed Pink

                    "GOLD" ->
                        Decode.succeed Gold

                    "GREEN" ->
                        Decode.succeed Green

                    "WHITE" ->
                        Decode.succeed White

                    "DARK" ->
                        Decode.succeed Dark

                    _ ->
                        Decode.fail ("Invalid PersonEyeColor type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : PersonEyeColor -> String
toString enum =
    case enum of
        Unknown ->
            "UNKNOWN"

        Blue ->
            "BLUE"

        Yellow ->
            "YELLOW"

        Red ->
            "RED"

        Brown ->
            "BROWN"

        Bluegrey ->
            "BLUEGREY"

        Black ->
            "BLACK"

        Orange ->
            "ORANGE"

        Hazel ->
            "HAZEL"

        Pink ->
            "PINK"

        Gold ->
            "GOLD"

        Green ->
            "GREEN"

        White ->
            "WHITE"

        Dark ->
            "DARK"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe PersonEyeColor
fromString enumString =
    case enumString of
        "UNKNOWN" ->
            Just Unknown

        "BLUE" ->
            Just Blue

        "YELLOW" ->
            Just Yellow

        "RED" ->
            Just Red

        "BROWN" ->
            Just Brown

        "BLUEGREY" ->
            Just Bluegrey

        "BLACK" ->
            Just Black

        "ORANGE" ->
            Just Orange

        "HAZEL" ->
            Just Hazel

        "PINK" ->
            Just Pink

        "GOLD" ->
            Just Gold

        "GREEN" ->
            Just Green

        "WHITE" ->
            Just White

        "DARK" ->
            Just Dark

        _ ->
            Nothing
