-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.PersonHairColor exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The hair color of this person. Will be "UNKNOWN" if not known or null if the person does not have hair.
-}
type PersonHairColor
    = Auburn
    | Black
    | Blonde
    | Brown
    | Grey
    | Unknown
    | White


list : List PersonHairColor
list =
    [ Auburn, Black, Blonde, Brown, Grey, Unknown, White ]


decoder : Decoder PersonHairColor
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "AUBURN" ->
                        Decode.succeed Auburn

                    "BLACK" ->
                        Decode.succeed Black

                    "BLONDE" ->
                        Decode.succeed Blonde

                    "BROWN" ->
                        Decode.succeed Brown

                    "GREY" ->
                        Decode.succeed Grey

                    "UNKNOWN" ->
                        Decode.succeed Unknown

                    "WHITE" ->
                        Decode.succeed White

                    _ ->
                        Decode.fail ("Invalid PersonHairColor type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : PersonHairColor -> String
toString enum =
    case enum of
        Auburn ->
            "AUBURN"

        Black ->
            "BLACK"

        Blonde ->
            "BLONDE"

        Brown ->
            "BROWN"

        Grey ->
            "GREY"

        Unknown ->
            "UNKNOWN"

        White ->
            "WHITE"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe PersonHairColor
fromString enumString =
    case enumString of
        "AUBURN" ->
            Just Auburn

        "BLACK" ->
            Just Black

        "BLONDE" ->
            Just Blonde

        "BROWN" ->
            Just Brown

        "GREY" ->
            Just Grey

        "UNKNOWN" ->
            Just Unknown

        "WHITE" ->
            Just White

        _ ->
            Nothing
