-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.PlanetOrderBy exposing (..)

import Json.Decode as Decode exposing (Decoder)


type PlanetOrderBy
    = CreatedAt_ASC
    | CreatedAt_DESC
    | Diameter_ASC
    | Diameter_DESC
    | Gravity_ASC
    | Gravity_DESC
    | Id_ASC
    | Id_DESC
    | IsPublished_ASC
    | IsPublished_DESC
    | Name_ASC
    | Name_DESC
    | OrbitalPeriod_ASC
    | OrbitalPeriod_DESC
    | Population_ASC
    | Population_DESC
    | RotationPeriod_ASC
    | RotationPeriod_DESC
    | SurfaceWater_ASC
    | SurfaceWater_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC


list : List PlanetOrderBy
list =
    [ CreatedAt_ASC, CreatedAt_DESC, Diameter_ASC, Diameter_DESC, Gravity_ASC, Gravity_DESC, Id_ASC, Id_DESC, IsPublished_ASC, IsPublished_DESC, Name_ASC, Name_DESC, OrbitalPeriod_ASC, OrbitalPeriod_DESC, Population_ASC, Population_DESC, RotationPeriod_ASC, RotationPeriod_DESC, SurfaceWater_ASC, SurfaceWater_DESC, UpdatedAt_ASC, UpdatedAt_DESC ]


decoder : Decoder PlanetOrderBy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "diameter_ASC" ->
                        Decode.succeed Diameter_ASC

                    "diameter_DESC" ->
                        Decode.succeed Diameter_DESC

                    "gravity_ASC" ->
                        Decode.succeed Gravity_ASC

                    "gravity_DESC" ->
                        Decode.succeed Gravity_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "isPublished_ASC" ->
                        Decode.succeed IsPublished_ASC

                    "isPublished_DESC" ->
                        Decode.succeed IsPublished_DESC

                    "name_ASC" ->
                        Decode.succeed Name_ASC

                    "name_DESC" ->
                        Decode.succeed Name_DESC

                    "orbitalPeriod_ASC" ->
                        Decode.succeed OrbitalPeriod_ASC

                    "orbitalPeriod_DESC" ->
                        Decode.succeed OrbitalPeriod_DESC

                    "population_ASC" ->
                        Decode.succeed Population_ASC

                    "population_DESC" ->
                        Decode.succeed Population_DESC

                    "rotationPeriod_ASC" ->
                        Decode.succeed RotationPeriod_ASC

                    "rotationPeriod_DESC" ->
                        Decode.succeed RotationPeriod_DESC

                    "surfaceWater_ASC" ->
                        Decode.succeed SurfaceWater_ASC

                    "surfaceWater_DESC" ->
                        Decode.succeed SurfaceWater_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    _ ->
                        Decode.fail ("Invalid PlanetOrderBy type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : PlanetOrderBy -> String
toString enum =
    case enum of
        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        Diameter_ASC ->
            "diameter_ASC"

        Diameter_DESC ->
            "diameter_DESC"

        Gravity_ASC ->
            "gravity_ASC"

        Gravity_DESC ->
            "gravity_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        IsPublished_ASC ->
            "isPublished_ASC"

        IsPublished_DESC ->
            "isPublished_DESC"

        Name_ASC ->
            "name_ASC"

        Name_DESC ->
            "name_DESC"

        OrbitalPeriod_ASC ->
            "orbitalPeriod_ASC"

        OrbitalPeriod_DESC ->
            "orbitalPeriod_DESC"

        Population_ASC ->
            "population_ASC"

        Population_DESC ->
            "population_DESC"

        RotationPeriod_ASC ->
            "rotationPeriod_ASC"

        RotationPeriod_DESC ->
            "rotationPeriod_DESC"

        SurfaceWater_ASC ->
            "surfaceWater_ASC"

        SurfaceWater_DESC ->
            "surfaceWater_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe PlanetOrderBy
fromString enumString =
    case enumString of
        "createdAt_ASC" ->
            Just CreatedAt_ASC

        "createdAt_DESC" ->
            Just CreatedAt_DESC

        "diameter_ASC" ->
            Just Diameter_ASC

        "diameter_DESC" ->
            Just Diameter_DESC

        "gravity_ASC" ->
            Just Gravity_ASC

        "gravity_DESC" ->
            Just Gravity_DESC

        "id_ASC" ->
            Just Id_ASC

        "id_DESC" ->
            Just Id_DESC

        "isPublished_ASC" ->
            Just IsPublished_ASC

        "isPublished_DESC" ->
            Just IsPublished_DESC

        "name_ASC" ->
            Just Name_ASC

        "name_DESC" ->
            Just Name_DESC

        "orbitalPeriod_ASC" ->
            Just OrbitalPeriod_ASC

        "orbitalPeriod_DESC" ->
            Just OrbitalPeriod_DESC

        "population_ASC" ->
            Just Population_ASC

        "population_DESC" ->
            Just Population_DESC

        "rotationPeriod_ASC" ->
            Just RotationPeriod_ASC

        "rotationPeriod_DESC" ->
            Just RotationPeriod_DESC

        "surfaceWater_ASC" ->
            Just SurfaceWater_ASC

        "surfaceWater_DESC" ->
            Just SurfaceWater_DESC

        "updatedAt_ASC" ->
            Just UpdatedAt_ASC

        "updatedAt_DESC" ->
            Just UpdatedAt_DESC

        _ ->
            Nothing
