-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.SpeciesOrderBy exposing (..)

import Json.Decode as Decode exposing (Decoder)


type SpeciesOrderBy
    = AverageHeight_ASC
    | AverageHeight_DESC
    | AverageLifespan_ASC
    | AverageLifespan_DESC
    | Classification_ASC
    | Classification_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC
    | Designation_ASC
    | Designation_DESC
    | Id_ASC
    | Id_DESC
    | IsPublished_ASC
    | IsPublished_DESC
    | Language_ASC
    | Language_DESC
    | Name_ASC
    | Name_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC


list : List SpeciesOrderBy
list =
    [ AverageHeight_ASC, AverageHeight_DESC, AverageLifespan_ASC, AverageLifespan_DESC, Classification_ASC, Classification_DESC, CreatedAt_ASC, CreatedAt_DESC, Designation_ASC, Designation_DESC, Id_ASC, Id_DESC, IsPublished_ASC, IsPublished_DESC, Language_ASC, Language_DESC, Name_ASC, Name_DESC, UpdatedAt_ASC, UpdatedAt_DESC ]


decoder : Decoder SpeciesOrderBy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "averageHeight_ASC" ->
                        Decode.succeed AverageHeight_ASC

                    "averageHeight_DESC" ->
                        Decode.succeed AverageHeight_DESC

                    "averageLifespan_ASC" ->
                        Decode.succeed AverageLifespan_ASC

                    "averageLifespan_DESC" ->
                        Decode.succeed AverageLifespan_DESC

                    "classification_ASC" ->
                        Decode.succeed Classification_ASC

                    "classification_DESC" ->
                        Decode.succeed Classification_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "designation_ASC" ->
                        Decode.succeed Designation_ASC

                    "designation_DESC" ->
                        Decode.succeed Designation_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "isPublished_ASC" ->
                        Decode.succeed IsPublished_ASC

                    "isPublished_DESC" ->
                        Decode.succeed IsPublished_DESC

                    "language_ASC" ->
                        Decode.succeed Language_ASC

                    "language_DESC" ->
                        Decode.succeed Language_DESC

                    "name_ASC" ->
                        Decode.succeed Name_ASC

                    "name_DESC" ->
                        Decode.succeed Name_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    _ ->
                        Decode.fail ("Invalid SpeciesOrderBy type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : SpeciesOrderBy -> String
toString enum =
    case enum of
        AverageHeight_ASC ->
            "averageHeight_ASC"

        AverageHeight_DESC ->
            "averageHeight_DESC"

        AverageLifespan_ASC ->
            "averageLifespan_ASC"

        AverageLifespan_DESC ->
            "averageLifespan_DESC"

        Classification_ASC ->
            "classification_ASC"

        Classification_DESC ->
            "classification_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        Designation_ASC ->
            "designation_ASC"

        Designation_DESC ->
            "designation_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        IsPublished_ASC ->
            "isPublished_ASC"

        IsPublished_DESC ->
            "isPublished_DESC"

        Language_ASC ->
            "language_ASC"

        Language_DESC ->
            "language_DESC"

        Name_ASC ->
            "name_ASC"

        Name_DESC ->
            "name_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe SpeciesOrderBy
fromString enumString =
    case enumString of
        "averageHeight_ASC" ->
            Just AverageHeight_ASC

        "averageHeight_DESC" ->
            Just AverageHeight_DESC

        "averageLifespan_ASC" ->
            Just AverageLifespan_ASC

        "averageLifespan_DESC" ->
            Just AverageLifespan_DESC

        "classification_ASC" ->
            Just Classification_ASC

        "classification_DESC" ->
            Just Classification_DESC

        "createdAt_ASC" ->
            Just CreatedAt_ASC

        "createdAt_DESC" ->
            Just CreatedAt_DESC

        "designation_ASC" ->
            Just Designation_ASC

        "designation_DESC" ->
            Just Designation_DESC

        "id_ASC" ->
            Just Id_ASC

        "id_DESC" ->
            Just Id_DESC

        "isPublished_ASC" ->
            Just IsPublished_ASC

        "isPublished_DESC" ->
            Just IsPublished_DESC

        "language_ASC" ->
            Just Language_ASC

        "language_DESC" ->
            Just Language_DESC

        "name_ASC" ->
            Just Name_ASC

        "name_DESC" ->
            Just Name_DESC

        "updatedAt_ASC" ->
            Just UpdatedAt_ASC

        "updatedAt_DESC" ->
            Just UpdatedAt_DESC

        _ ->
            Nothing
