-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.VehicleOrderBy exposing (..)

import Json.Decode as Decode exposing (Decoder)


type VehicleOrderBy
    = CargoCapacity_ASC
    | CargoCapacity_DESC
    | Class_ASC
    | Class_DESC
    | Consumables_ASC
    | Consumables_DESC
    | CostInCredits_ASC
    | CostInCredits_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC
    | Crew_ASC
    | Crew_DESC
    | Id_ASC
    | Id_DESC
    | IsPublished_ASC
    | IsPublished_DESC
    | Length_ASC
    | Length_DESC
    | MaxAtmospheringSpeed_ASC
    | MaxAtmospheringSpeed_DESC
    | Model_ASC
    | Model_DESC
    | Name_ASC
    | Name_DESC
    | Passengers_ASC
    | Passengers_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC


list : List VehicleOrderBy
list =
    [ CargoCapacity_ASC, CargoCapacity_DESC, Class_ASC, Class_DESC, Consumables_ASC, Consumables_DESC, CostInCredits_ASC, CostInCredits_DESC, CreatedAt_ASC, CreatedAt_DESC, Crew_ASC, Crew_DESC, Id_ASC, Id_DESC, IsPublished_ASC, IsPublished_DESC, Length_ASC, Length_DESC, MaxAtmospheringSpeed_ASC, MaxAtmospheringSpeed_DESC, Model_ASC, Model_DESC, Name_ASC, Name_DESC, Passengers_ASC, Passengers_DESC, UpdatedAt_ASC, UpdatedAt_DESC ]


decoder : Decoder VehicleOrderBy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "cargoCapacity_ASC" ->
                        Decode.succeed CargoCapacity_ASC

                    "cargoCapacity_DESC" ->
                        Decode.succeed CargoCapacity_DESC

                    "class_ASC" ->
                        Decode.succeed Class_ASC

                    "class_DESC" ->
                        Decode.succeed Class_DESC

                    "consumables_ASC" ->
                        Decode.succeed Consumables_ASC

                    "consumables_DESC" ->
                        Decode.succeed Consumables_DESC

                    "costInCredits_ASC" ->
                        Decode.succeed CostInCredits_ASC

                    "costInCredits_DESC" ->
                        Decode.succeed CostInCredits_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "crew_ASC" ->
                        Decode.succeed Crew_ASC

                    "crew_DESC" ->
                        Decode.succeed Crew_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "isPublished_ASC" ->
                        Decode.succeed IsPublished_ASC

                    "isPublished_DESC" ->
                        Decode.succeed IsPublished_DESC

                    "length_ASC" ->
                        Decode.succeed Length_ASC

                    "length_DESC" ->
                        Decode.succeed Length_DESC

                    "maxAtmospheringSpeed_ASC" ->
                        Decode.succeed MaxAtmospheringSpeed_ASC

                    "maxAtmospheringSpeed_DESC" ->
                        Decode.succeed MaxAtmospheringSpeed_DESC

                    "model_ASC" ->
                        Decode.succeed Model_ASC

                    "model_DESC" ->
                        Decode.succeed Model_DESC

                    "name_ASC" ->
                        Decode.succeed Name_ASC

                    "name_DESC" ->
                        Decode.succeed Name_DESC

                    "passengers_ASC" ->
                        Decode.succeed Passengers_ASC

                    "passengers_DESC" ->
                        Decode.succeed Passengers_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    _ ->
                        Decode.fail ("Invalid VehicleOrderBy type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : VehicleOrderBy -> String
toString enum =
    case enum of
        CargoCapacity_ASC ->
            "cargoCapacity_ASC"

        CargoCapacity_DESC ->
            "cargoCapacity_DESC"

        Class_ASC ->
            "class_ASC"

        Class_DESC ->
            "class_DESC"

        Consumables_ASC ->
            "consumables_ASC"

        Consumables_DESC ->
            "consumables_DESC"

        CostInCredits_ASC ->
            "costInCredits_ASC"

        CostInCredits_DESC ->
            "costInCredits_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        Crew_ASC ->
            "crew_ASC"

        Crew_DESC ->
            "crew_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        IsPublished_ASC ->
            "isPublished_ASC"

        IsPublished_DESC ->
            "isPublished_DESC"

        Length_ASC ->
            "length_ASC"

        Length_DESC ->
            "length_DESC"

        MaxAtmospheringSpeed_ASC ->
            "maxAtmospheringSpeed_ASC"

        MaxAtmospheringSpeed_DESC ->
            "maxAtmospheringSpeed_DESC"

        Model_ASC ->
            "model_ASC"

        Model_DESC ->
            "model_DESC"

        Name_ASC ->
            "name_ASC"

        Name_DESC ->
            "name_DESC"

        Passengers_ASC ->
            "passengers_ASC"

        Passengers_DESC ->
            "passengers_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe VehicleOrderBy
fromString enumString =
    case enumString of
        "cargoCapacity_ASC" ->
            Just CargoCapacity_ASC

        "cargoCapacity_DESC" ->
            Just CargoCapacity_DESC

        "class_ASC" ->
            Just Class_ASC

        "class_DESC" ->
            Just Class_DESC

        "consumables_ASC" ->
            Just Consumables_ASC

        "consumables_DESC" ->
            Just Consumables_DESC

        "costInCredits_ASC" ->
            Just CostInCredits_ASC

        "costInCredits_DESC" ->
            Just CostInCredits_DESC

        "createdAt_ASC" ->
            Just CreatedAt_ASC

        "createdAt_DESC" ->
            Just CreatedAt_DESC

        "crew_ASC" ->
            Just Crew_ASC

        "crew_DESC" ->
            Just Crew_DESC

        "id_ASC" ->
            Just Id_ASC

        "id_DESC" ->
            Just Id_DESC

        "isPublished_ASC" ->
            Just IsPublished_ASC

        "isPublished_DESC" ->
            Just IsPublished_DESC

        "length_ASC" ->
            Just Length_ASC

        "length_DESC" ->
            Just Length_DESC

        "maxAtmospheringSpeed_ASC" ->
            Just MaxAtmospheringSpeed_ASC

        "maxAtmospheringSpeed_DESC" ->
            Just MaxAtmospheringSpeed_DESC

        "model_ASC" ->
            Just Model_ASC

        "model_DESC" ->
            Just Model_DESC

        "name_ASC" ->
            Just Name_ASC

        "name_DESC" ->
            Just Name_DESC

        "passengers_ASC" ->
            Just Passengers_ASC

        "passengers_DESC" ->
            Just Passengers_DESC

        "updatedAt_ASC" ->
            Just UpdatedAt_ASC

        "updatedAt_DESC" ->
            Just UpdatedAt_DESC

        _ ->
            Nothing
