-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type AddToFilmPlanetsPayload
    = AddToFilmPlanetsPayload


type AddToFilmSpeciesPayload
    = AddToFilmSpeciesPayload


type AddToFilmStarshipsPayload
    = AddToFilmStarshipsPayload


type AddToFilmVehiclesPayload
    = AddToFilmVehiclesPayload


type AddToPeopleFilmPayload
    = AddToPeopleFilmPayload


type AddToPeoplePlanetPayload
    = AddToPeoplePlanetPayload


type AddToPeopleSpeciesPayload
    = AddToPeopleSpeciesPayload


type AddToPeopleStarshipsPayload
    = AddToPeopleStarshipsPayload


type AddToPeopleVehiclesPayload
    = AddToPeopleVehiclesPayload


type Asset
    = Asset


type AssetPreviousValues
    = AssetPreviousValues


type AssetSubscriptionPayload
    = AssetSubscriptionPayload


type Film
    = Film


type FilmPreviousValues
    = FilmPreviousValues


type FilmSubscriptionPayload
    = FilmSubscriptionPayload


type InvokeFunctionPayload
    = InvokeFunctionPayload


type Person
    = Person


type PersonPreviousValues
    = PersonPreviousValues


type PersonSubscriptionPayload
    = PersonSubscriptionPayload


type Planet
    = Planet


type PlanetPreviousValues
    = PlanetPreviousValues


type PlanetSubscriptionPayload
    = PlanetSubscriptionPayload


type QueryMeta_
    = QueryMeta_


type RemoveFromFilmPlanetsPayload
    = RemoveFromFilmPlanetsPayload


type RemoveFromFilmSpeciesPayload
    = RemoveFromFilmSpeciesPayload


type RemoveFromFilmStarshipsPayload
    = RemoveFromFilmStarshipsPayload


type RemoveFromFilmVehiclesPayload
    = RemoveFromFilmVehiclesPayload


type RemoveFromPeopleFilmPayload
    = RemoveFromPeopleFilmPayload


type RemoveFromPeoplePlanetPayload
    = RemoveFromPeoplePlanetPayload


type RemoveFromPeopleSpeciesPayload
    = RemoveFromPeopleSpeciesPayload


type RemoveFromPeopleStarshipsPayload
    = RemoveFromPeopleStarshipsPayload


type RemoveFromPeopleVehiclesPayload
    = RemoveFromPeopleVehiclesPayload


type Species
    = Species


type SpeciesPreviousValues
    = SpeciesPreviousValues


type SpeciesSubscriptionPayload
    = SpeciesSubscriptionPayload


type Starship
    = Starship


type StarshipPreviousValues
    = StarshipPreviousValues


type StarshipSubscriptionPayload
    = StarshipSubscriptionPayload


type Vehicle
    = Vehicle


type VehiclePreviousValues
    = VehiclePreviousValues


type VehicleSubscriptionPayload
    = VehicleSubscriptionPayload
