-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Country exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
code : SelectionSet Api.ScalarCodecs.Id Api.Object.Country
code =
    Object.selectionForField "ScalarCodecs.Id" "code" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
name : SelectionSet String Api.Object.Country
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| -}
native : SelectionSet String Api.Object.Country
native =
    Object.selectionForField "String" "native" [] Decode.string


{-| -}
phone : SelectionSet String Api.Object.Country
phone =
    Object.selectionForField "String" "phone" [] Decode.string


{-| -}
continent : SelectionSet decodesTo Api.Object.Continent -> SelectionSet decodesTo Api.Object.Country
continent object_ =
    Object.selectionForCompositeField "continent" [] object_ identity


{-| -}
capital : SelectionSet (Maybe String) Api.Object.Country
capital =
    Object.selectionForField "(Maybe String)" "capital" [] (Decode.string |> Decode.nullable)


{-| -}
currency : SelectionSet (Maybe String) Api.Object.Country
currency =
    Object.selectionForField "(Maybe String)" "currency" [] (Decode.string |> Decode.nullable)


{-| -}
languages : SelectionSet decodesTo Api.Object.Language -> SelectionSet (List decodesTo) Api.Object.Country
languages object_ =
    Object.selectionForCompositeField "languages" [] object_ (identity >> Decode.list)


{-| -}
emoji : SelectionSet String Api.Object.Country
emoji =
    Object.selectionForField "String" "emoji" [] Decode.string


{-| -}
emojiU : SelectionSet String Api.Object.Country
emojiU =
    Object.selectionForField "String" "emojiU" [] Decode.string


{-| -}
states : SelectionSet decodesTo Api.Object.State -> SelectionSet (List decodesTo) Api.Object.Country
states object_ =
    Object.selectionForCompositeField "states" [] object_ (identity >> Decode.list)
